# Generated by Django 6.0.6 on 2026-07-02 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
                'db_table': 'questionario',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PesoPergunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Peso de Pergunta',
                'verbose_name_plural': 'Pesos de Pergunta',
                'db_table': 'peso_pergunta',
                'ordering': ['codigo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='uq_peso_pergunta_codigo_ativo')],
            },
        ),
        migrations.CreateModel(
            name='VersaoQuestionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_versao', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='question.questionario')),
            ],
            options={
                'verbose_name': 'Versão de Questionário',
                'verbose_name_plural': 'Versões de Questionário',
                'db_table': 'versao_questionario',
                'ordering': ['questionario', 'numero_versao'],
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField()),
                ('versao_questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secoes', to='question.versaoquestionario')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'db_table': 'secao',
                'ordering': ['versao_questionario', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField()),
                ('versao_questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimensoes', to='question.versaoquestionario')),
            ],
            options={
                'verbose_name': 'Dimensão',
                'verbose_name_plural': 'Dimensões',
                'db_table': 'dimensao',
                'ordering': ['versao_questionario', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('identificador', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('texto_ajuda', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField()),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
                ('dimensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='question.dimensao')),
                ('peso_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='question.pesopergunta')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='question.secao')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'db_table': 'pergunta',
                'ordering': ['secao', 'ordem'],
                'indexes': [models.Index(fields=['secao', 'ordem'], name='idx_pergunta_ordem'), models.Index(fields=['dimensao'], name='idx_pergunta_dimensao')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('identificador',), name='uq_pergunta_identificador_ativo')],
            },
        ),
        migrations.AddIndex(
            model_name='versaoquestionario',
            index=models.Index(fields=['status'], name='idx_versao_status'),
        ),
        migrations.AddConstraint(
            model_name='versaoquestionario',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('questionario', 'numero_versao'), name='uq_versao_questionario_numero_ativo'),
        ),
        migrations.AddIndex(
            model_name='secao',
            index=models.Index(fields=['versao_questionario', 'ordem'], name='idx_secao_ordem'),
        ),
        migrations.AddIndex(
            model_name='dimensao',
            index=models.Index(fields=['versao_questionario', 'ordem'], name='idx_dimensao_ordem'),
        ),
        migrations.AddConstraint(
            model_name='dimensao',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('versao_questionario', 'codigo'), name='uq_dimensao_codigo_versao_ativo'),
        ),
    ]
